apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mysql-deployment.yaml
- wordpress-deployment.yaml
- netpol.yaml

secretGenerator:
- name: mysql-pass
  literals:
  - password=changePW

patches:
- path: ./fqdn.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: wp-ing