apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mysql-deployment.yaml
- wordpress-deployment.yaml
- netpol.yaml

configMapGenerator:
- name: wp-cm 
  behavior: create
  literals:
  - MYSQL_DATABASE=wordpress
  - MYSQL_USER=jclin

secretGenerator:
- name: wp-secret 
  behavior: create
  literals:
  - MYSQL_ROOT_PASSWORD=changeit
  - MYSQL_PASSWORD=jclin29722

patches:
- path: ./fqdn.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: wp-ing