apiVersion: v1
kind: Service
metadata:
  name: mysql-hsvc
  labels:
    name: mysql-hsvc
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: wordpress-po
  # headless service
  clusterIP: None
---
apiVersion: apps/v1
# can use stateful set, stateful set allows a fixed name unlike deployment (stateless)
# stateful set name: wpdb-sts-0
# deployment name: wordpress-mysql-5dc54599cf-j44st
# stateful allows a fixed FQDN to the pod
kind: StatefulSet
metadata:
  name: wordpress-db-sts
  labels:
    name: wordpress-db-sts
spec:
  replicas: 1
  serviceName: wordpress-mysql
  selector:
    matchLabels:
      name: wordpress-po
  volumeClaimTemplates:
  - metadata:
      name: mysql-pv-claim
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: do-block-storage 
  template:
    metadata:
      name: wordpress-po
      labels:
        name: wordpress-po
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: wp-cm
        - secretRef:
            name: wp-secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pv-claim
          mountPath: /var/lib/mysql
