---
# Only allow wordpress access to DB
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-netpol
  labels:
    name: mysql-netpol
spec:
  podSelector:
    matchLabels:
      name: mysql-po
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: wordpress-po
    ports:
    - port: 3306
      protocol: TCP
---
# rule to allow ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-netpol
  labels:
    name: ingress-netpol
spec:
  podSelector:
    matchLabels:
      name: wordpress-po
  policyTypes:
  - Ingress
  ingress:
  - from: 
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      podSelector:
        matchExpressions:
        - key: app.kubernetes.io/component
          operator: In
          values: 
          - controller
        - key: app.kubernetes.io/instance
          operator: In
          values: 
          # name of the ingress-nginx, specified when running helm install
          - cfdsa-jul25
        - key: app.kubernetes.io/name
          operator: In
          values:
          - ingress-nginx