---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: dov-cm
  labels:
    name: dov-cm
data:
  INSTANCE_NAME: myapp
---
apiVersion: v1 
kind: Secret 
metadata:
  name: dov-secret
  labels:
    name: dov-secret
type: Opaque
data:
  db_password: ZW50ZXI= 
