---
# config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
  labels:
    name: bgg-cm
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local
---
# secrets
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  labels:
    name: bgg-secret
type: Opaque
data:
  # pw (changeit) need to be base64 encoded
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=