apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: wpns

commonLabels:
  tenant: wpns
    
# namePrefix: wpns-

configMapGenerator:
- name: wp-cm 
  behavior: merge
  literals:
  - MYSQL_DATABASE=wpnsdb
  - MYSQL_USER=jclin

secretGenerator:
- name: wp-secret 
  behavior: merge
  literals:
  - MYSQL_ROOT_PASSWORD=changeit
  - MYSQL_PASSWORD=jclin29722

patches:
- path: ./fqdn.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: wp-ing