---
# deployments
# 3 dash is to demarcate a config, can have multiple configs ina file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  # mandatory to have labels
  labels:
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    # e.g there could be multiple instances of dov-bear running but how to know which instances belong to this deployment?
    # the matchLabels follow the template label name to ensure instances belong to this deployment, does not need to be name, could be other fields and multiple fields
    matchLabels:
      name: bggapp-po
  # following specifies pod
  template:
    metadata:
      name: bggapp-po
      labels:
        name: bggapp-po
    spec:
      containers:
      # array
      - name: bgg-application
        image: stackupiss/bgg-backend:v1
      # following controls how to handle when there is no image
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
---
# accessing the application section (clusterIP, NodePort)
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  # provide internal IP address (within cloud)
  # type: ClusterIP
  # type: NodePort
  # LoadBalancer will provide external IP, can check using kubectl get po,deploy,svc -nmyns -owide
  type: LoadBalancer
  selector:
    name: bggapp-po
  ports:
  # service port 80
  - port: 80
    targetPort: 3000