---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: dov-deploy
  labels:
    name: dov-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dov-po
  template: 
    metadata:
      name: dov-po
      labels:
        name: dov-po
    spec:
      containers:
      - name: dov-bear
        image: chukmunnlee/dov-bear:v1
        imagePullPolicy: IfNotPresent
        #env:
        #- name: INSTANCE_HASH
        #  valueFrom: 
        #    fieldRef:
        #      fieldPath: status.podIP
        #envFrom:
        #- configMapRef: 
        #    name: dov-cm
        #- secretRef: 
        #    name: dov-secret
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000

---
apiVersion: v1 
kind: Service 
metadata:
  name: dov-svc
  labels:
    name: dov-svc
spec:
  type: ClusterIP
  selector: 
    name: dov-po
  ports:
  - port: 3000
    targetPort: 3000
