---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: dov-deploy
  labels:
    name: dov-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dov-po
  template: 
    metadata:
      name: dov-po
      labels:
        name: dov-po
    spec:
      containers:
      - name: dov-bear
        image: chukmunnlee/dov-bear:v1
        imagePullPolicy: IfNotPresent
        #env:
        #- name: INSTANCE_HASH
        #  valueFrom: 
        #    fieldRef:
        #      fieldPath: status.podIP
        #envFrom:
        #- configMapRef: 
        #    name: dov-cm
        #- secretRef: 
        #    name: dov-secret
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000

---
apiVersion: v1 
kind: Service 
metadata:
  name: dov-svc
  labels:
    name: dov-svc
spec:
  type: ClusterIP
  selector: 
    name: dov-po
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-netpol
  labels:
    name: deny-all
spec:
  podSelector:
    matchLabels:
      name: dov-po
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-port-80
  labels:
    name: access-port-80
spec:
  podSelector:
    matchLabels:
      name: dov-po
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          # only allow containers with this label to access
          http-access: allow
    ports:
    # set the port of the container not the service! common mistake
    - port: 3000
---
# example 9 - allow DNS access
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dns
  labels:
    name: dns
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - to:
    # to block google access
    # only can block IP address, cannot block hostname
    # - ipBlock:
    #     cidr: 8.8.8.8/0
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP